// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pepswcruhahyeuosykyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcHN3Y3J1aGFoeWV1b3N5a3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDQ2MDMsImV4cCI6MjA2NTIyMDYwM30.PexE8JTafYBBsN3E7Wlp4F29NeVQLw9TCW1ZVPGEups";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);